### ISSUE TITLE
java.io.IOException: java.security.ProviderException: Failed to generate key pair.

### ISSUE THREAD

**Issue by gclawes** [GrapheneOS/Auditor#183]
Failing to generate an audit key pair on a Pixel 3 XL.

Relevant logs from `adb logcat`:
```
04-04 17:51:03.140   715   715 E android.hardware.keymaster@4.1-service.citadel: GenerateKey : device response error code: INVALID_ARGUMENT
04-04 17:51:03.141   743   743 E keystore2: keystore2::error: In generate_key.
04-04 17:51:03.141   743   743 E keystore2:
04-04 17:51:03.141   743   743 E keystore2: Caused by:
04-04 17:51:03.141   743   743 E keystore2:     0: While generating Key without explicit attestation key.
04-04 17:51:03.141   743   743 E keystore2:     1: Error::Km(ErrorCode(-38))
04-04 17:51:03.142  4865  5005 E GenerateAttestationService: attestation generation error
04-04 17:51:03.142  4865  5005 E GenerateAttestationService: java.io.IOException: java.security.ProviderException: Failed to generate key pair.
04-04 17:51:03.142  4865  5005 E GenerateAttestationService: 	at u1.f.i(Unknown Source:16)
04-04 17:51:03.142  4865  5005 E GenerateAttestationService: 	at u1.f.j(Unknown Source:13)
04-04 17:51:03.142  4865  5005 E GenerateAttestationService: 	at app.attestation.auditor.GenerateAttestationService.onHandleIntent(Unknown Source:73)
04-04 17:51:03.142  4865  5005 E GenerateAttestationService: 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:78)
04-04 17:51:03.142  4865  5005 E GenerateAttestationService: 	at android.os.Handler.dispatchMessage(Handler.java:106)
04-04 17:51:03.142  4865  5005 E GenerateAttestationService: 	at android.os.Looper.loopOnce(Looper.java:201)
04-04 17:51:03.142  4865  5005 E GenerateAttestationService: 	at android.os.Looper.loop(Looper.java:288)
04-04 17:51:03.142  4865  5005 E GenerateAttestationService: 	at android.os.HandlerThread.run(HandlerThread.java:67)
04-04 17:51:03.142  4865  5005 E GenerateAttestationService: Caused by: java.security.ProviderException: Failed to generate key pair.
04-04 17:51:03.142  4865  5005 E GenerateAttestationService: 	at android.security.keystore2.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPairHelper(AndroidKeyStoreKeyPairGeneratorSpi.java:620)
04-04 17:51:03.142  4865  5005 E GenerateAttestationService: 	at android.security.keystore2.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:545)
04-04 17:51:03.142  4865  5005 E GenerateAttestationService: 	at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:727)
04-04 17:51:03.142  4865  5005 E GenerateAttestationService: 	at u1.f.i(Unknown Source:9)
04-04 17:51:03.142  4865  5005 E GenerateAttestationService: 	... 7 more
04-04 17:51:03.142  4865  5005 E GenerateAttestationService: Caused by: android.security.KeyStoreException: Invalid argument
04-04 17:51:03.142  4865  5005 E GenerateAttestationService: 	at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:356)
04-04 17:51:03.142  4865  5005 E GenerateAttestationService: 	at android.security.KeyStoreSecurityLevel.handleExceptions(KeyStoreSecurityLevel.java:57)
04-04 17:51:03.142  4865  5005 E GenerateAttestationService: 	at android.security.KeyStoreSecurityLevel.generateKey(KeyStoreSecurityLevel.java:145)
04-04 17:51:03.142  4865  5005 E GenerateAttestationService: 	at android.security.keystore2.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPairHelper(AndroidKeyStoreKeyPairGeneratorSpi.java:587)
04-04 17:51:03.142  4865  5005 E GenerateAttestationService: 	... 10 more
```

**Comment by thestinger** [comment]
This was an OS issue which will be resolved in today's GrapheneOS release. It was caused by Android 12.1 assuming that a bug was fixed in the firmware and the Pixel 3 / Pixel 3 XL firmware is no longer maintained. It will start working again after today's release where we reverted the change for the Pixel 3 / Pixel 3 XL.

**Comment by gclawes** [comment]
Sweet, awesome response time!  Glad it's fixed, I'll look for the new release.
